version: '3.5'

services:
  postgres:
    container_name: monorepo-pg
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
      - ./scripts/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    ports:
      - "54322:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: monorepo-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: